// Auto-generated by scripts/generate-version.sh — do not edit
public enum GitVersion {
    public static let commitHash = "6319646"
    public static let commitMessage = "fix: derive tmux server name from repo path, add critical rules to CLAUDE.md"
}
