// Auto-generated by scripts/generate-version.sh — do not edit
public enum GitVersion {
    public static let commitHash = "4e07f32"
    public static let commitMessage = "docs: update project references"
}
