// Auto-generated by scripts/generate-version.sh — do not edit
public enum GitVersion {
    public static let commitHash = "4b62696"
    public static let commitMessage = "fix: wrap tmux new-window commands in shell -ic so arguments work"
}
