-- Gate for the reconcile arm that judges holder-backed session rows: the third
-- of the pty-holder transport's named reconcilers, alongside
-- gc_holder_rendezvous_enabled (unlinks files) and reap_holder_children_enabled
-- (signals processes). This one deletes terminal and tab rows on its own
-- judgement, with no user gesture, so it soaks behind its own switch rather
-- than riding pty_holder_enabled — that outer gate has to be ON to exercise the
-- transport at all, so it cannot express "transport on, one destructive sweep
-- at a time", which is the whole protocol the sibling gates exist for.
--
-- No DEFAULT clause, deliberately. ADD COLUMN ... DEFAULT would backfill every
-- existing row, destroying the distinction between "nobody has chosen" (NULL)
-- and "chose off" (0) — which is what made auto_hibernate_enabled impossible to
-- graduate without a forcing UPDATE that also reset deliberate opt-ins.
-- The shipped default lives in exactly one place:
-- Config.holderRowReconcileEnabledDefault.
ALTER TABLE config ADD COLUMN holder_row_reconcile_enabled INTEGER;
