#!/usr/bin/env bash
# Writes Sources/TBDShared/GitVersion.swift with the current git short hash.
# Called automatically by restart.sh before building.
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/Sources/TBDShared/GitVersion.swift"

HASH=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
MSG=$(git -C "$REPO_ROOT" log -1 --format=%s 2>/dev/null || echo "")
# Escape for Swift string literal: backslashes, double quotes, backticks, and dollar signs
MSG=$(printf '%s' "$MSG" | sed 's/\\/\\\\/g; s/"/\\"/g')

NEW_CONTENT="// Auto-generated by scripts/generate-version.sh — do not edit
public enum GitVersion {
    public static let commitHash = \"$HASH\"
    public static let commitMessage = \"$MSG\"
}"

# Only write if content changed (avoids unnecessary recompilation)
if [ -f "$OUT" ] && [ "$(cat "$OUT")" = "$NEW_CONTENT" ]; then
    exit 0
fi

printf '%s\n' "$NEW_CONTENT" > "$OUT"
