#!/usr/bin/env bash
# Writes Sources/TBDShared/GitVersion.swift with the current git short hash.
# Called automatically by restart.sh before building.
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/Sources/TBDShared/GitVersion.swift"

HASH=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > "$OUT" <<EOF
// Auto-generated by scripts/generate-version.sh — do not edit
public enum GitVersion {
    public static let commitHash = "$HASH"
}
EOF
